/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Projetoapp.GUI;

/**
 *
 * @author vfelinto54
 */
public class RemoverProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemoverProduto
     */
    public RemoverProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaRemoverP = new javax.swing.JTable();
        btRemoverPro = new javax.swing.JButton();
        btFecharRemovP = new javax.swing.JButton();

        tabelaRemoverP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaRemoverP);

        btRemoverPro.setText("Remover");
        btRemoverPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverProActionPerformed(evt);
            }
        });

        btFecharRemovP.setText("Fechar");
        btFecharRemovP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharRemovPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRemoverPro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btFecharRemovP)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRemoverPro)
                    .addComponent(btFecharRemovP))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRemoverProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRemoverProActionPerformed

    private void btFecharRemovPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharRemovPActionPerformed
        this.dispose();
    }//GEN-LAST:event_btFecharRemovPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFecharRemovP;
    private javax.swing.JButton btRemoverPro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaRemoverP;
    // End of variables declaration//GEN-END:variables
}
